// Rotating hero copy, kept here so it's easy to audit/edit in one place.
// - FUN_ROLES: single words for the "Companion for ___" eyebrow (cycles on a timer).
// - HERO_LINES: [hook, payoff] pairs for the headline (one picked at random per open).
// Keep HERO_LINES[0] as the original line so SSR + first paint stay stable.

/** @type {string[]} */
export const FUN_ROLES = [
  "adventurers", "button mashers", "cozy gamers", "loot goblins", "speedrunners",
  "backseat gamers", "tryhards", "sweatlords", "keyboard warriors", "dungeon divers",
  "boss slayers", "quest chasers", "completionists", "achievement hunters",
  "trophy collectors", "lore nerds", "min-maxers", "theorycrafters", "grinders",
  "campers", "snipers", "healers", "tanks", "DPS mains", "solo queuers", "guildmates",
  "raid bosses", "PvP demons", "couch co-oppers", "retro heads", "pixel peepers",
  "ragequitters", "save scummers", "potion hoarders", "fast travelers",
  "easter-egg hunters", "glitch hunters", "sequence breakers", "100-percenters",
  "permadeath survivors", "roguelike addicts", "gacha addicts", "wallet warriors",
  "F2P heroes", "meta slaves", "wiki lurkers", "blind runners", "first-try legends",
  "3am raiders", "snack-powered gamers", "controller throwers", "WASD wizards",
  "quickscopers", "clutch masters", "comeback kings", "respawn regulars",
  "lategame legends", "mod hoarders", "cheat-code kids", "konami-code knowers",
  "puzzle ponderers", "low-HP gamblers", "last-stand heroes", "dodge-roll addicts",
  "parry gods", "stealth sneakers", "chaos gremlins", "chest openers",
  "NPC befrienders", "cutscene enjoyers", "fog-of-war clearers", "map completionists",
  "side-quest addicts", "one-more-turners", "loot sorters", "hardcore heroes",
  "casual legends", "pixel pilgrims", "boss-rush fiends", "no-hit runners",
  "lucky crit-fishers", "rng sufferers", "patch-note readers", "hitbox scientists",
  "frame-perfect freaks", "combo dreamers", "spawn campers", "map hackers (jk)",
  "mini-map addicts", "fanfic writers", "headcanon holders", "ship captains",
  "emote spammers", "GG sayers", "rage-quit royalty", "loot-box gamblers",
  "endgame grinders", "secret finders", "speedrun timers", "forever-stuck heroes",
];

/** @type {Array<[string, string]>} */
export const HERO_LINES = [
  ["Stuck?", "Keep playing."],
  ["Lost the plot?", "Find your way."],
  ["Hit a wall?", "Walk right through."],
  ["Boss too tough?", "Bring it down."],
  ["No idea where to go?", "We do."],
  ["Softlocked?", "Not for long."],
  ["Rage building?", "Take a breath."],
  ["Puzzle won't budge?", "Nudge it."],
  ["Can't find the exit?", "It's this way."],
  ["One-shot again?", "Let's fix that."],
  ["Missed the turn?", "Circle back."],
  ["Out of ideas?", "We're not."],
  ["Grinding forever?", "Skip the guesswork."],
  ["Where's that key?", "We'll point you."],
  ["Chest still locked?", "Grab the loot."],
  ["Wrong build?", "Respec smarter."],
  ["Dying at the same spot?", "Change that."],
  ["Guide didn't help?", "This will."],
  ["Story lost you?", "Catch up fast."],
  ["Stuck on a side quest?", "Wrap it up."],
  ["Can't beat the timer?", "Beat it."],
  ["Level too hard?", "Even the odds."],
  ["Missing a collectible?", "Hunt it down."],
  ["Combat feels unfair?", "Turn it around."],
  ["New game, new wall?", "Same fix."],
  ["Progress stalled?", "Get moving."],
  ["Confused by the map?", "Read it with us."],
  ["Which path is right?", "This one."],
  ["Enemy keeps winning?", "Not anymore."],
  ["Fell for the trap?", "Dodge the next."],
  ["Backtracking again?", "Save the trip."],
  ["Feeling underleveled?", "Level the field."],
  ["Riddle got you?", "Solve it."],
  ["Same death, tenth time?", "Make it the last."],
  ["Can't crack the boss pattern?", "We can."],
  ["Lost your bearings?", "Get them back."],
  ["Quest marker gone?", "Follow ours."],
  ["Menu overload?", "Cut through it."],
  ["Stuck mid-dungeon?", "Get out clean."],
  ["No walkthrough handy?", "You've got one."],
  ["Secret still hidden?", "Not from us."],
  ["Timer running out?", "Make it count."],
  ["Boss phase two got you?", "Phase three's next."],
  ["Wrong item every time?", "Grab the right one."],
  ["Map's a maze?", "We know the way."],
  ["Can't parry that?", "You will."],
  ["Endgame wall?", "Break it."],
  ["Tutorial long gone?", "Quick refresher."],
  ["Where to next?", "Right here."],
  ["Still stuck?", "Not for long."],
];
